### ISSUE TITLE
Not accepting passphrase

### ISSUE THREAD

**Issue by jhmblvd** [vtorrent/vTorrent-Client#5]
I bought vtorrent a long time ago, but I back up my keys in three places and print them. I could not get the wallet to work when I first tried. It took me almost 3 weeks till I found a short video on how to add clients. The wallet finally worked but now it's not accepting my passphrase?  Is there a new wallet? I really have had  a rough time getting help and support with this coin but believed in it's mission. Now I can't open the client wallet and am not sure what to do.

**Comment by vtorrent** [comment]
Dear all,The second release candidate for vTorrent Core v0.8.2.1 (RC2) for Windows and Mac are ready for testing.This release (v0.8.2.1) is mainly focus on improvement and usability of the client (UX/UI) which all will be carry over once/if our ZEC's based zero-knowledge fork is ready, superseded the current version which is mostly based on ShadowCash with our own improvements.Windowshttps://www.dropbox.com/s/gb5tkh5rdijk29h/vtorrent_rc2_0821.zip* shasum256  f6b4b01cdd412bf71a571bbeb742336d2ec466b833405443a7517b05d693954a* md5sum  649911205da71546353546d4cb6e9738Machttps://www.dropbox.com/s/t55suc6c7amtgi6/vTorrent-0.8.2.1-RC2-MacOS.zip* shasum256  5f19b4ab27c8912265fff1fc3d74a52d80a8887c7d0cb39b8b0b29d25ea0466e* md5sum  eee65d2dd6f00565ee88878fc66effb7Fixes since RC1    •    All Runtime Error should be fixed    •    Issues with Debug console     •    Better compiler optimization Test items should cover (v0.8.2.1)    •    All basic wallet related features (Under Wallet Menu)    •    Wallet Management features for HD wallet creation/import    •    Chat related features (Focus on Private only for now as Group chat is being work on)    •    Wallet encryption including 2FA    •    In-Client Trading (Focus on most basic functions, advance features is still being work on)    •    Overall stability of the wallet    •    Crashes (Runtime error on Windows)Please kindly feedback your suggestions or especially if you happen to find any bugs.Thank you all for your kind support.Regards,vTorrent                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: December 29, 2017 11:59 PMTo: vTorrent-Client@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [vtorrent/vTorrent-Client] Not accepting passphrase (#5)  I bought vtorrent a long time ago, but I back up my keys in three places and print them. I could not get the wallet to work when I first tried. It took me almost 3 weeks till I found a short video on how to add clients. The wallet finally worked but now it's not accepting my passphrase?  Is there a new wallet? I really have had  a rough time getting help and support with this coin but believed in it's mission. Now I can't open the client wallet and am not sure what to do.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jhmblvd** [comment]
Thanks
